sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

install:
  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  # elm
  - npm install -g elm@0.18.0 elm-test@0.18.9
  - make setup

script:
  - make setup
  - make build

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.stack


addons:
  apt:
    packages:
      - libgmp-dev
    sources:
      - hvr-ghc

