name: pollution-info-service
version: 0.1.2
author:
- mat646
- kaskadz
git: https://github.com/mat646/pollution-info-service.git

dependencies:
  - base
  - warp
  - aeson
  - wai-make-assets
  - servant-elm
  - servant
  - http-client
  - wai
  - servant-server
  - transformers
  - containers
  - time

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src

tests:
  unit:
    main: AppUnit.hs
    ghc-options: -main-is AppUnit
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - HUnit
  quickcheck:
    main: AppQuickCheck.hs
    ghc-options: -main-is AppQuickCheck
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - QuickCheck
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
